language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t yusuf/client:v0 Dockerfile .
script:
  - docker run -e CI=true -it yusuf/client:v0 npm run test -- --coverage
